# Generated by Django 3.0.3 on 2020-02-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thunb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thunb',
            new_name='thumb',
        ),
    ]
