# Generated by Django 3.0.3 on 2020-02-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro',
        ),
    ]
